server:
  port: 8083

spring:
  application:
    name: ptf-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: secret
  profiles:
    active: dev
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 5MB
      max-request-size: 50MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

file:
  projectDir: save-project-imgs
